/**
 * Risidio
 * This is a web server to connect stackchain 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: arun.enjoys@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface MintnftNftnameBody { 
    /**
     * Updated name of the NFT
     */
    name?: string;
    /**
     * Updated status of the NFT
     */
    status?: string;
}